# Generated by Django 2.2 on 2019-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korisnik',
            options={'verbose_name_plural': 'korisnici'},
        ),
        migrations.AlterModelOptions(
            name='poraka',
            options={'verbose_name_plural': 'poraki'},
        ),
        migrations.AlterModelOptions(
            name='predmet',
            options={'verbose_name_plural': 'predmeti'},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'verbose_name_plural': 'temi'},
        ),
        migrations.AddField(
            model_name='predmet',
            name='naslov_id',
            field=models.CharField(default='test-123', max_length=200),
            preserve_default=False,
        ),
    ]
