# Generated by Django 2.2 on 2019-06-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190522_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='ime',
            field=models.CharField(default='Asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='korisnik',
            name='prezime',
            field=models.CharField(default='Bsd', max_length=100),
            preserve_default=False,
        ),
    ]
