# Generated by Django 2.2 on 2019-06-04 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_poraka_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poraka',
            name='avtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poraki', to='app.Korisnik'),
        ),
        migrations.AlterField(
            model_name='poraka',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poraki', to='app.Tema'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='avtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temi', to='app.Korisnik'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='predmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temi', to='app.Predmet'),
        ),
    ]
